server:
  port: 9999
spring:
  application:
    name: dicovery-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#  Optional
  datacenter: On-premise-Bare-Metal
  environment: dev


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF