server:
  port: 8282
spring:
  security:
    user:
      name: arfat
      password: pass123
      roles: ADMIN,USER

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password
      scope: READ,WRITE_PROFILE
    authorization:
      check-token-access: permitAll